#!/bin/bash
source .env

user="ubuntu"
host="api.usecasetechnologies.com"
destination="/home/ubuntu/doc-comparison/"

rsync -avzh --exclude deploy --exclude venv --exclude .git --exclude .vscode --exclude .env --exclude uploads --exclude README.md --exclude  "__pycache__/" . $user@$host:$destination

ssh $user@$host <<ENDSSH
    cd $destination
    sudo docker compose down
    sudo docker compose up -d
    exit
ENDSSH
