#!/bin/bash

user="ubuntu"
host="192.168.1.99"
destination="/home/ubuntu/doc-comparison/"

rsync -avzh --exclude deploy --exclude venv --exclude .git --exclude .vscode --exclude .env --exclude uploads --exclude README.md --exclude  "__pycache__/" . $user@$host:$destination

ssh $user@$host <<ENDSSH
    cd $destination
    sudo docker compose down
    sudo docker compose up -d
    exit
ENDSSH
