version: '3.8'
services:
  doc-comparison:
    build: .
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./templates:/app/templates
      - ./.env:/app/.env
      - ./uploads:/app/uploads
      - ./app.py:/app/app.py
    working_dir: /app
    command: "python3 app.py"
    env_file:
      - .env
    ports:
      - 8000
    networks:
          - npm_default
networks:
  npm_default:
    external: true


